# This will be the first part of the title tag for your site
# <title> {{site.name}} </title>
# ============================================================
name: "snippet.love - HTML, CSS, and JavaScript hors d'oeuvres"

# Populates the meta description for the site. Should be under 150 characters for best SEO results.
# ============================================================
description: "snippet.love - HTML, CSS, and JavaScript hors d'oeuvres, i.e. code snippets"

# Owner (organization or individual) of site content
# ============================================================
author: "sprout &amp; co + dgmd"

# Change this to your production URL
# ============================================================
url: "http://dgmd.github.io/snippet.love"

# Publish future posts or not option.
# ============================================================
future: true

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ============================================================
exclude: [README.md, Rakefile, node_modules]

# Pagination variable for how many posts to show in a list
# ============================================================
#paginate: 5

# Style of permalinks
# ============================================================
permalink: pretty

# Variable format options for URL styles below
# ============================================================
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-:day-:year/:title.html/                 => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                  => /blog/2009/04/29/slap-chop/index.html


# ============================================================
# ============================================================

highlighter: rouge

kramdown:
  input: GFM

collections:
  snippets:
    output: true
    permalink: /snippets/:slug